import { MD3Typescale } from "react-native-paper/lib/typescript/types";

export const fontTheme: Partial<MD3Typescale> = {
  displayLarge: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 57,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 45,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 36,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: "Roboto-Regular",
    fontWeight: "500",
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: "Roboto-Regular",
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: "Roboto-Regular",
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: "Roboto-Regular",
    fontWeight: "500",
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: "Roboto-Regular",
    fontWeight: "500",
    fontSize: 11,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
};
